export const QueryKeys = Object.freeze({
  POKEMON_LIST: 'POKEMON_LIST',
  POKEMON_SEARCH: 'POKEMON_SEARCH',
  POKEMON_LOCAL_NAMES: 'POKEMON_LOCAL_NAMES',
  POKEMON_DETAIL: 'POKEMON_DETAIL',
  POKEMON_SPECIES: 'POKEMON_SPECIES',
  POKEMON_EVOLUTION_CHAIN: 'POKEMON_EVOLUTION_CHAIN',
});
